### PR TITLE
[fix] Enable easy DEBUG log level for Microcks containers

### LINKED ISSUE #191: Allow setting `DEBUG` log level on containers
### Reason/Context

See https://github.com/microcks/microcks-testcontainers-java/issues/260

As of today, we don't have an easy way to set the `DEBUG` log level on containers, which makes things difficult to diagnose in case of an issue or unexpected behavior. 

But since https://github.com/microcks/microcks/issues/1867 we now have an easy way to change the log levels.

### Description

The goal of this feature is to allow users to set up more verbose log levels, enabling them to gain deeper insights into what's going wrong when retrieving the containers' logs by piping their output to specific consumers.

### Implementation ideas

We can add either a `WithDebugLogLevel()` on the `MicrocksContainer` class. Calling this method before startup will allow to set the correct environment variables. We also need the same things on `MicrocksContainerEnsemble` for both the microcks and the microcks-async-minion containers.

### PR DESCRIPTION
**Pull request by sunnynagavo**
# Pull Request

## Proposed Changes

This pull request introduces a convenient way to enable DEBUG-level logging in Microcks containers, making it easier to troubleshoot issues by increasing log verbosity. The changes add new methods and environment variable handling to the builder classes, update the ensemble logic to propagate the debug setting, and document the feature in the README.

**Debug Logging Support:**

* Added `WithDebugLogLevel()` methods to `MicrocksBuilder`, `MicrocksAsyncMinionBuilder`, and `MicrocksContainerEnsemble` to enable DEBUG logging by setting the appropriate environment variables for both the main Microcks container and the async minion (Quarkus) container. [[1]](diffhunk://#diff-6443a9fe5b1867aabc1b4b1a9884520c5f3532f6b0f29b339aece21e32c9657fR281-R288) [[2]](diffhunk://#diff-cf81adac3b89203e88e8734dfd99f68936039eec037dc668da75ce677b4d9930R136-R164) [[3]](diffhunk://#diff-eba97eac39bdef74564c80952171cd2f86549d183bbfd53ff2def2e0df551fa5R231-R248)
* Modified `MicrocksContainerEnsemble` to track when DEBUG logging is enabled and to ensure the setting is applied to both containers, regardless of the order in which features are enabled. [[1]](diffhunk://#diff-eba97eac39bdef74564c80952171cd2f86549d183bbfd53ff2def2e0df551fa5R37-R38) [[2]](diffhunk://#diff-eba97eac39bdef74564c80952171cd2f86549d183bbfd53ff2def2e0df551fa5R191-R195)

Fixes #191

**Documentation:**

* Updated the `README.md` with clear instructions and code examples showing how to enable DEBUG logs for single containers and ensembles using the new builder methods.

**Constants and Environment Variables:**

* Added new constants for environment variable names and values related to logging levels in both `MicrocksBuilder` and `MicrocksAsyncMinionBuilder` to centralize configuration and improve maintainability. [[1]](diffhunk://#diff-6443a9fe5b1867aabc1b4b1a9884520c5f3532f6b0f29b339aece21e32c9657fR41-R50) [[2]](diffhunk://#diff-cf81adac3b89203e88e8734dfd99f68936039eec037dc668da75ce677b4d9930R136-R164)

### Author/Contributor

- [X] If documentation is needed for this change, has that been included in this pull request
- [x] run `dotnet test` and ensure you have test coverage for the lines you are introducing
- [ ] run `dotnet husky run` and fix any issues that you have introduced

### Reviewer

- [] Label as either `feature`, `fix`, `documentation`, `enhancement`, `maintenance` or `breaking`

### CODE REVIEW

**Comment by sunnynagavo** [comment]
@lbroudoux  I will add few tests in next commit. 

provide me with early feedback.

File: src/Microcks.Testcontainers/MicrocksAsyncMinionBuilder.cs [hunk 1]
```diff
@@ -133,4 +133,33 @@ public MicrocksAsyncMinionBuilder WithAmqpConnection(GenericConnection amqpConne
...
+
+    /// <summary>
+    /// Environment variable name used by Quarkus to configure console log level.
+    /// </summary>
+    public const string QuarkusConsoleLogLevelEnvVar = "QUARKUS_LOG_CONSOLE_LEVEL";
+
+    /// <summary>
+    /// Environment variable name used by Quarkus to configure the Microcks category log level.
+    /// </summary>
+    public const string QuarkusMicrocksCategoryLogLevelEnvVar = "QUARKUS_LOG_CATEGORY__IO_GITHUB_MICROCKS__LEVEL";
```
Comment (SebastienDegodez) [inline src/Microcks.Testcontainers/MicrocksAsyncMinionBuilder.cs]:
```suggestion
    private const string QuarkusMicrocksCategoryLogLevelEnvVar = "QUARKUS_LOG_CATEGORY__IO_GITHUB_MICROCKS__LEVEL";
```

File: src/Microcks.Testcontainers/MicrocksContainerEnsemble.cs [hunk 2]
```diff
@@ -221,6 +228,24 @@ public MicrocksContainerEnsemble WithAmqpConnection(GenericConnection amqpConnec
...
+    /// Enables DEBUG log level for the containers of this ensemble.
+    /// </summary>
+    /// <remarks>
+    /// Applies to the main Microcks container (Spring) and, when the async feature is enabled,
+    /// to the async-minion container (Quarkus).
+    /// </remarks>
+    public MicrocksContainerEnsemble WithDebugLogLevel()
+    {
+        this._debugLogLevelEnabled = true;
+        this._microcksBuilder.WithDebugLogLevel();
```
Comment (SebastienDegodez) [inline src/Microcks.Testcontainers/MicrocksContainerEnsemble.cs]: In TestContainers, Builders are immutable: WithDebugLogLevel() returns a new instance, so we must reassign it.
```suggestion
        this._microcksBuilder = this._microcksBuilder.WithDebugLogLevel();
```

File: src/Microcks.Testcontainers/MicrocksBuilder.cs [hunk 3]
```diff
@@ -38,6 +38,16 @@ public sealed class MicrocksBuilder : ContainerBuilder<MicrocksBuilder, Microcks
     /// </summary>
     public const ushort MicrocksGrpcPort = 9090;
 
+    /// <summary>
+    /// Environment variable name used to configure Microcks logging level for the Microcks package.
+    /// </summary>
+    public const string MicrocksLoggingLevelEnvVar = "LOGGING_LEVEL_IO_GITHUB_MICROCKS";
```
Comment (SebastienDegodez) [inline src/Microcks.Testcontainers/MicrocksBuilder.cs]:
```suggestion
    private const string MicrocksLoggingLevelEnvVar = "LOGGING_LEVEL_IO_GITHUB_MICROCKS";
```

**Comment by lbroudoux** [comment]
> I like it, but I'll wait for the tests before merging it.
> 
> How do you test this? I don’t know if TestContainers provides a method to inspect environment variables, but since this is a container, I think using Exec with `printenv` could work.

In the Java library, I have tested by inspecting the containers logs and checking that the `DEBUG` header set by logback was present.

File: README.md [hunk 4]
```diff
@@ -221,6 +221,36 @@ await TestcontainersSettings.ExposeHostPortsAsync(ports)
     .ConfigureAwait(false);
 ```
 
+### Enabling DEBUG logs in Microcks containers
```
[the remark this answers is not in the document]
Comment (sunnynagavo) [reply README.md]: replaced with just troubleshotting section at the end of the file

**Comment by sunnynagavo** [comment]
> I like it, but I'll wait for the tests before merging it.
> 
> How do you test this? I don’t know if TestContainers provides a method to inspect environment variables, but since this is a container, I think using Exec with `printenv` could work.

Yup, I will spend some time on the tests. change was simple to do even though I am not super familiar with this repo but for writing tests, I need sometime haha and I will follow @lbroudoux  suggestion to look at the java library. will send new commit soonish

**Comment by sunnynagavo** [comment]
Thank you @SebastienDegodez , I need your help in merging this. lets gooo :)

**Review by sunnynagavo — COMMENTED** [review]
LGTM

**Comment by sunnynagavo** [comment]
@lbroudoux gentle ping on this, could you review and merge if its all good

**Comment by sunnynagavo** [comment]
> Looks all good to me. Thanks!

Thank you so much. I will work on the other issue then

**Comment by sunnynagavo** [comment]
@lbroudoux can you also add more issues if there are any outstanding ones needs to be addressed so that I can take a look. Thanks
